apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  namespace: kube-public
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath: 
    path: /home/k8s
