---
- hosts: k8
  remote_user: root
  tasks:
  - name: install cfssl
    shell: mkdir /root/bin && curl -s -L -o /root/bin/cfssl https://pkg.cfssl.org/R1.2/cfssl_linux-amd64 && curl -s -L -o /root/bin/cfssljson https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64 && chmod +x /root/bin/{cfssl,cfssljson} && echo 'export PATH=$PATH:/root/bin' >> /etc/bashrc && source /etc/bashrc

 

