---
- hosts: k8
  remote_user: root
  tasks:
  - name: copy daemon.json to remote host
    copy: src=./daemon.json dest=/etc/docker/daemon.json backup=yes
  - name: restart remote docker 
    service: name=docker state=restarted
